// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailEdiGateway.Infrastructure.Persistence;

#nullable disable

namespace RetailEdiGateway.Infrastructure.Persistence.Migrations
{
 [DbContext(typeof(ApplicationDbContext))]
 [Migration("20260602075731_InitialCreate")]
 partial class InitialCreate
 {
 /// <inheritdoc />
 protected override void BuildTargetModel(ModelBuilder modelBuilder)
 {
#pragma warning disable 612, 618
 modelBuilder
 .HasAnnotation("ProductVersion", "8.0.2")
 .HasAnnotation("Relational:MaxIdentifierLength", 63);

 NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.Campaign", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTime>("DeliveryDeadline")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(255)
 .HasColumnType("character varying(255)");

 b.Property<DateTime>("StartDate")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("Status")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.HasKey("Id");

 b.ToTable("campaigns", (string)null);

 b.HasData(
 new
 {
 Id = new Guid("11111111-1111-1111-1111-111111111111"),
 DeliveryDeadline = new DateTime(2026, 5, 28, 23, 59, 59, 0, DateTimeKind.Utc),
 Name = "Italian Week 2026",
 StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
 Status = "Active"
 },
 new
 {
 Id = new Guid("22222222-2222-2222-2222-222222222222"),
 DeliveryDeadline = new DateTime(2026, 6, 10, 23, 59, 59, 0, DateTimeKind.Utc),
 Name = "Spring Gardening Week 2026",
 StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
 Status = "Scheduled"
 });
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.EdiTransaction", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Direction")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<string>("ErrorMessage")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<string>("MessageType")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<string>("Payload")
 .IsRequired()
 .HasColumnType("text");

 b.Property<DateTime>("ProcessedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("PurchaseOrderId")
 .HasColumnType("uuid");

 b.Property<int>("RetryCount")
 .ValueGeneratedOnAdd()
 .HasColumnType("integer")
 .HasDefaultValue(0);

 b.Property<string>("Status")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.HasKey("Id");

 b.HasIndex("PurchaseOrderId");

 b.ToTable("edi_transactions", (string)null);
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrder", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<Guid>("CampaignId")
 .HasColumnType("uuid");

 b.Property<DateTime>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("ErpOrderNumber")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<string>("Status")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<Guid>("SupplierId")
 .HasColumnType("uuid");

 b.HasKey("Id");

 b.HasIndex("ErpOrderNumber")
 .IsUnique();

 b.HasIndex("SupplierId");

 b.HasIndex("CampaignId", "Status");

 b.ToTable("purchase_orders", (string)null);

 b.HasData(
 new
 {
 Id = new Guid("55555555-5555-5555-5555-555555555555"),
 CampaignId = new Guid("11111111-1111-1111-1111-111111111111"),
 CreatedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
 ErpOrderNumber = "PO-2026-001",
 Status = "Sent",
 SupplierId = new Guid("33333333-3333-3333-3333-333333333333")
 },
 new
 {
 Id = new Guid("66666666-6666-6666-6666-666666666666"),
 CampaignId = new Guid("22222222-2222-2222-2222-222222222222"),
 CreatedAt = new DateTime(2026, 5, 20, 14, 30, 0, 0, DateTimeKind.Utc),
 ErpOrderNumber = "PO-2026-002",
 Status = "Draft",
 SupplierId = new Guid("44444444-4444-4444-4444-444444444444")
 });
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrderLine", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTime?>("ConfirmedDate")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("ConfirmedQty")
 .HasColumnType("integer");

 b.Property<int>("OrderedQty")
 .HasColumnType("integer");

 b.Property<string>("ProductCode")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<string>("ProductName")
 .IsRequired()
 .HasMaxLength(255)
 .HasColumnType("character varying(255)");

 b.Property<Guid>("PurchaseOrderId")
 .HasColumnType("uuid");

 b.Property<DateTime>("RequestedDate")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("Status")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.HasKey("Id");

 b.HasIndex("PurchaseOrderId", "ProductCode");

 b.ToTable("purchase_order_lines", (string)null);

 b.HasData(
 new
 {
 Id = new Guid("77777777-7777-7777-7777-777777777777"),
 ConfirmedQty = 0,
 OrderedQty = 10000,
 ProductCode = "8001234567890",
 ProductName = "Spaghetti Pasta 500g",
 PurchaseOrderId = new Guid("55555555-5555-5555-5555-555555555555"),
 RequestedDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
 Status = "Pending"
 },
 new
 {
 Id = new Guid("88888888-8888-8888-8888-888888888888"),
 ConfirmedQty = 0,
 OrderedQty = 5000,
 ProductCode = "8009876543210",
 ProductName = "Extra Virgin Olive Oil 1L",
 PurchaseOrderId = new Guid("55555555-5555-5555-5555-555555555555"),
 RequestedDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
 Status = "Pending"
 },
 new
 {
 Id = new Guid("99999999-9999-9999-9999-999999999999"),
 ConfirmedQty = 0,
 OrderedQty = 1500,
 ProductCode = "4001122334455",
 ProductName = "Garden Tool Set",
 PurchaseOrderId = new Guid("66666666-6666-6666-6666-666666666666"),
 RequestedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
 Status = "Pending"
 });
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.Supplier", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<string>("ContactEmail")
 .IsRequired()
 .HasMaxLength(255)
 .HasColumnType("character varying(255)");

 b.Property<string>("IntegrationType")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(255)
 .HasColumnType("character varying(255)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("suppliers", (string)null);

 b.HasData(
 new
 {
 Id = new Guid("33333333-3333-3333-3333-333333333333"),
 Code = "SUPP-ITA-01",
 ContactEmail = "contact@italianfood.it",
 IntegrationType = "EDIFACT",
 Name = "Italian Food Distributors S.p.A."
 },
 new
 {
 Id = new Guid("44444444-4444-4444-4444-444444444444"),
 Code = "SUPP-DEO-02",
 ContactEmail = "info@gartendeko.de",
 IntegrationType = "XML",
 Name = "Garten und Deko GmbH"
 });
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.WarehouseSlot", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("BayNumber")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.Property<DateTime>("BookedTime")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("DcCode")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<bool>("IsSyncedToWms")
 .HasColumnType("boolean");

 b.Property<Guid>("PurchaseOrderLineId")
 .HasColumnType("uuid");

 b.Property<string>("Status")
 .IsRequired()
 .HasMaxLength(50)
 .HasColumnType("character varying(50)");

 b.HasKey("Id");

 b.HasIndex("PurchaseOrderLineId");

 b.ToTable("warehouse_slots", (string)null);
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.EdiTransaction", b =>
 {
 b.HasOne("RetailEdiGateway.Core.Entities.PurchaseOrder", "PurchaseOrder")
 .WithMany("EdiTransactions")
 .HasForeignKey("PurchaseOrderId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("PurchaseOrder");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrder", b =>
 {
 b.HasOne("RetailEdiGateway.Core.Entities.Campaign", "Campaign")
 .WithMany("Orders")
 .HasForeignKey("CampaignId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("RetailEdiGateway.Core.Entities.Supplier", "Supplier")
 .WithMany("Orders")
 .HasForeignKey("SupplierId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.Navigation("Campaign");

 b.Navigation("Supplier");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrderLine", b =>
 {
 b.HasOne("RetailEdiGateway.Core.Entities.PurchaseOrder", "PurchaseOrder")
 .WithMany("Lines")
 .HasForeignKey("PurchaseOrderId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("PurchaseOrder");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.WarehouseSlot", b =>
 {
 b.HasOne("RetailEdiGateway.Core.Entities.PurchaseOrderLine", "PurchaseOrderLine")
 .WithMany("WarehouseSlots")
 .HasForeignKey("PurchaseOrderLineId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("PurchaseOrderLine");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.Campaign", b =>
 {
 b.Navigation("Orders");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrder", b =>
 {
 b.Navigation("EdiTransactions");

 b.Navigation("Lines");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.PurchaseOrderLine", b =>
 {
 b.Navigation("WarehouseSlots");
 });

 modelBuilder.Entity("RetailEdiGateway.Core.Entities.Supplier", b =>
 {
 b.Navigation("Orders");
 });
#pragma warning restore 612, 618
 }
 }
}
